### ISSUE TITLE
Feather ESP32-S3 TFT REV CRC Error

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/Adafruit_CircuitPython_HTU31D#12]
Running the example [htu31d_simpletest.py](https://github.com/adafruit/Adafruit_CircuitPython_HTU31D/blob/main/examples/htu31d_simpletest.py) code for on the Feather ESP32-S3 TFT Reverse fails with a CRC error.

CircuitPython : 8.2.2
Library Bundle : 20230807
Bootloader : 0.16.0

The fix is easy enough. Slow down the I2C bus to 70 kHz or less.

`i2c = busio.I2C(board.SCL, board.SDA, frequency=70_000) `

error message:

```Found HTU31D with serial number 0x3474900
Heater is on? True
Heater is on? False
Traceback (most recent call last):
  File "code.py", line 20, in <module>
  File "adafruit_htu31d.py", line 181, in measurements
RuntimeError: Invalid CRC calculated

**Comment by dhalbert** [comment]
HTU31D works OK in CircuitPython 9.0.0-alpha.5. See https://github.com/adafruit/circuitpython/issues/7923. I don't believe this is fixable in CircuitPython 8.x.x, but the ESP-IDF updates we are using in 9.0.0 have corrected some fundamental I2C issues.
